export default new Model({
    id: '',
    ids: '',
    userId: '',
    enrollNumber: '',
    attrTime: '',
    attPeriod: '',
    workType: '',
    attType: '',
    auditStatus: '',
    bak: '',
    department: '',
    createTime: '',
    startAttrTime: '',
    endAttrTime: '',
    userName:'',
    recordingTime: '',
    details: '',
    reason: '',
    auditTime: '',
    page: '',
    size: '',
});