export default new Model({
  taskName: '',
  executor: '',
  page: '',
  size: '',
  ids: '',
  taskType: '',
  taskContent: '',
  projectInfo: '',
  planStartTime: '',
  planEndTime: '',
  planHours: '',
  priority: '',
  useHours: '',
  id: '',
  time: '',
  copyPerson: '',
  userId: '',
  uploadId: '',
  code: '',
  startDateStr: '',
  endDateStr: ''
});
