export default new Model({
  id: '',
  projectInfo: '',
  projectName: '',
  projectCode: '',
  projectLeader: '',
  projectType: '',
  planStartDate: '',
  planEndDate: '',
  realEndDate: '',
  realStartDate: '',
  days: '',
  projectContent: '',
  projectPower: '',
  idList: '',
  ids: '',
  memberId: '',
  memberName: '',
  position: '',
  team: '',
  uploadId: '',
  page: '',
  size: '',
  code: ''
});
